version: '3.8'

services:
  mongodb:
    image: mongo:${MONGO_VERSION}
    container_name: ${MONGO_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongodb_data:/data/db
    networks:
      - nps-network

  mongo-express:
    image: mongo-express
    container_name: ${MONGO_EXPRESS_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}"
    environment:
      - ME_CONFIG_MONGODB_SERVER=${MONGO_SERVER}
      - ME_CONFIG_MONGODB_PORT=${MONGO_PORT}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
    depends_on:
      - mongodb
    networks:
      - nps-network

volumes:
  mongodb_data:
    driver: local

networks:
  nps-network:
    name: ${NETWORK_NAME}
    driver: bridge
