services:
  frontend:
    build: .
    container_name: nps-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://nps-backend:3001
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - nps-network

networks:
  nps-network:
    external: true
    name: nps-network 